// app/layout.tsx (or pages/_app.tsx if using Pages Router)
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google"; // Import DM_Sans
import { Geist_Mono } from "next/font/google";
import "./globals.css";

// Setup DM_Sans
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ['400', '500', '700'], // Add weights you intend to use
  variable: "--font-dm-sans", // Define a CSS variable for DM Sans
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dmSans.variable} ${geistMono.variable} antialiased`}> {/* Use dmSans.variable */}
        {children}
      </body>
    </html>
  );
}